export default {
  LandingPage: "LandingPage",
  SignInScreen: "SignInScreen",
  SignUpScreenStep1: "SignUpScreenStep1",
  SignUpScreenStep2: "SignUpScreenStep2",
  SignUpScreenStep3: "SignUpScreenStep3",
  SignUpScreenStep4: "SignUpScreenStep4",
  SignUpScreenStep5: "SignUpScreenStep5 ",
  Home: "Home",
  PostScreen: "PostScreen",
  PostsScreen: "PostsScreen",
  Community: "Community",
  Chat: "Chat",
  ChatScreen: "ChatScreen",
  Notifications: "Notifications",
};
